<?php

namespace App\Http\Controllers\Reports;

use App\Http\Controllers\Controller;
use App\Services\CompanyService;
use Illuminate\Support\Facades\Auth;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use PhpOffice\PhpSpreadsheet\Style\Border;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Worksheet\Worksheet;

class BaseReportController extends Controller
{
    // ── Shared Excel header ──────────────────────────────────────────────────
    // All export methods across all report controllers call this.
    // Pass the sheet, report title, period dates and last column letter.

    protected function buildExcelHeader(
        Worksheet $sheet,
        string $reportTitle,
        string $dateFrom,
        string $dateTo,
        string $lastCol
    ): void {
        $company = CompanyService::get();

        // Row 1 — Company name
        $sheet->mergeCells('A1:'.$lastCol.'1');
        $sheet->setCellValue('A1', $company?->InstName ?? 'Prime Survivors International Ltd');
        $sheet->getStyle('A1')->getFont()->setBold(true)->setSize(14);
        $sheet->getStyle('A1')->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);

        // Row 2 — Report title
        $sheet->mergeCells('A2:'.$lastCol.'2');
        $sheet->setCellValue('A2', $reportTitle);
        $sheet->getStyle('A2')->getFont()->setBold(true)->setSize(11);
        $sheet->getStyle('A2')->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);

        // Row 3 — Period
        $sheet->mergeCells('A3:'.$lastCol.'3');
        $sheet->setCellValue('A3', 'Period: '.$dateFrom.' — '.$dateTo);
        $sheet->getStyle('A3')->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);

        // Row 4 — Generated by
        $sheet->mergeCells('A4:'.$lastCol.'4');
        $sheet->setCellValue('A4',
            'Generated: '.now()->format('d M Y, h:i A').
            '  |  By: '.(Auth::user()->FullName ?? Auth::user()->ID)
        );
        $sheet->getStyle('A4')->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);
        $sheet->getStyle('A4')->getFont()->setSize(9);
    }

    // ── Shared Excel column headers ──────────────────────────────────────────
    // Renders the blue header row. Pass the sheet, row number and headers array.
    // Returns the next available row number after the headers.

    protected function buildExcelColumnHeaders(
        Worksheet $sheet,
        int $row,
        array $headers
    ): int {
        $col = 'A';
        foreach ($headers as $header) {
            $sheet->setCellValue($col.$row, $header);
            $sheet->getStyle($col.$row)->getFont()->setBold(true);
            $sheet->getStyle($col.$row)->getFill()
                ->setFillType(Fill::FILL_SOLID)
                ->getStartColor()->setRGB('185FA5');
            $sheet->getStyle($col.$row)->getFont()->getColor()->setRGB('FFFFFF');
            $sheet->getStyle($col.$row)->getAlignment()
                ->setHorizontal(Alignment::HORIZONTAL_CENTER);
            $col++;
        }

        // Return the first data row
        return $row + 1;
    }

    // ── Shared Excel borders ─────────────────────────────────────────────────
    // Applies thin border to the full table range.

    protected function buildExcelBorders(
        Worksheet $sheet,
        int $headerRow,
        int $lastDataRow,
        string $lastCol
    ): void {
        if ($lastDataRow >= $headerRow) {
            $sheet->getStyle('A'.$headerRow.':'.$lastCol.$lastDataRow)
                ->getBorders()
                ->getAllBorders()
                ->setBorderStyle(Border::BORDER_THIN);
        }
    }

    // ── Shared Excel stream to browser ───────────────────────────────────────
    // Streams the spreadsheet as a download. Call at the end of every export.

    protected function streamExcel(
        \PhpOffice\PhpSpreadsheet\Spreadsheet $spreadsheet,
        string $filename
    ): void {
        header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
        header('Content-Disposition: attachment;filename="'.$filename.'"');
        header('Cache-Control: max-age=0');

        $writer = new \PhpOffice\PhpSpreadsheet\Writer\Xlsx($spreadsheet);
        $writer->save('php://output');
        exit;
    }
}
